# Description:
#   Displays the description for the requested error code.
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   hubot http code <code>
#
# Author:
#   Ajnasz

path = require('path')

getCodeMessage = (codeObj) ->
  'use strict'
  codeObj.code + ' is ' + codeObj.title + ', ' + codeObj.summary + ' ' + codeObj.descriptions.wikipedia.link

getNoCodeMessage = (code) ->
  'use strict'
  if code
    return 'No such code: ' + code
  'No such code'

getCodeStart = (code) ->
  'use strict'
  Math.floor code / 100

getCodesJSON = (code) ->
  'use strict'
  require(path.resolve(__dirname + '/..' + '/codes/' + getCodeStart(code) + '.json')).codes[code]

isValidCode = (code) ->
  'use strict'
  start = if code then getCodeStart(code) else null
  start >= 1 and start <= 5

module.exports = (robot) ->
  'use strict'
  robot.respond /http code (\d+)/i, (msg) ->
    message = undefined
    code = undefined
    codeObj = undefined
    code = msg.match[1]
    if isValidCode(code)
      codeObj = getCodesJSON(code)
      if codeObj
        message = getCodeMessage(codeObj)
      else
        message = getNoCodeMessage(code)
    else
      message = getNoCodeMessage(code)
    msg.send message
  return

# ---
# generated by js2coffee 2.0.1
